[package]
authors    = ["Jarrett Tierney <jmt@amazon.com>"]
edition    = "2024"
keywords   = ["edo"]
license    = "MIT OR Apache-2.0"
name       = "edo"
repository = "https://github.com/awslabs/edo"
version    = "0.1.0"

[dependencies]
arc-handle         = { workspace = true }
async-compression  = { workspace = true }
async-recursion    = { workspace = true }
async-trait        = { workspace = true }
base16             = { workspace = true }
base64             = { workspace = true }
bimap              = { workspace = true }
blake3             = { workspace = true }
bon                = { workspace = true }
daggy              = { workspace = true }
dashmap            = { workspace = true }
dialoguer          = { workspace = true }
duct               = { workspace = true }
flume              = { workspace = true }
futures            = { workspace = true }
handlebars         = { workspace = true }
home               = { workspace = true }
indexmap           = { workspace = true }
indicatif          = { workspace = true }
jiff               = { workspace = true }
names              = { workspace = true }
nutype             = { workspace = true }
ocilot             = { workspace = true }
os_pipe            = { workspace = true }
owo-colors         = { workspace = true }
parking_lot        = { workspace = true }
rand               = { workspace = true }
regex              = { workspace = true }
resolvo            = { workspace = true }
semver             = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
sha2               = { workspace = true }
snafu              = { workspace = true }
tempfile           = { workspace = true }
tokio              = { workspace = true }
tokio-util         = { workspace = true }
toml               = { workspace = true }
tracing            = { workspace = true }
tracing-appender   = { workspace = true }
tracing-subscriber = { workspace = true }
uuid               = { workspace = true }

[dev-dependencies]
mockall     = { workspace = true }
serial_test = { workspace = true }
