schema-version = "1"

[vendor.public-ecr]
kind = "image"
uri  = "public.ecr.aws/docker/library"

[requires.gcc]
kind       = "image"
at         = "=14.3.0"

[environment.gcc]
kind   = "container"
source = ["//hello_oci/gcc"]

[source.code]
kind       = "local"
path       = "hello_oci"
out        = "."
is_archive = false

[transform.build]
kind        = "script"
environment = "//hello_oci/gcc"
source      = ["//hello_oci/code"]
commands    = [
    "mkdir -p {{install-root}}/bin",
    "gcc -o hello_oci hello.c",
    "cp hello_oci {{install-root}}/bin/hello_oci"
]
