schema-version = "1"

[source.src]
kind       = "local"
path       = "hello_rust"
out        = "."
is_archive = false

[transform.code]
kind   = "import"
source = ["//hello_rust/src"]

[transform.vendor]
kind     = "script"
depends  = ["//hello_rust/code"]
commands = [
    "mkdir -p {{install-root}}/.cargo",
    "cargo vendor > vendor.toml",
    "cp -rf {{build-root}}/vendor {{install-root}}/vendor",
    "cp vendor.toml {{install-root}}/.cargo/config.toml"
]

[transform.build]
kind     = "script"
depends  = ["//hello_rust/code", "//hello_rust/vendor"]
commands = [
    "mkdir -p {{install-root}}/bin",
    "cargo build --offline --release",
    "cp target/release/hello_rust {{install-root}}/bin/hello_rust"
]
